---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: comments-api
  template:
    metadata:
      labels:
        name: comments-api
    spec:
      containers:
      - name: application
        image: "zanuar19/comments-api:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8008
        env:
          - name: DB_PORT
            value: "5432"
          - name: DB_HOST
            value: "rosie.db.elephantsql.com"
          - name: DB_PASSWORD
            value: "xEbzshAMcvfISgLC3mVYLkZyqZR4YEk8"
          - name: DB_TABLE
            value: "fwdagbzc"
          - name: DB_USERNAME
            value: "fwdagbzc"
          - name: SSL_MODE 